name: SITKA Scraper - Cartestraina

on:
  schedule:
    - cron: "0 5 * * 1"   # rulează în fiecare luni la 05:00 UTC
  workflow_dispatch:       # rulează manual din tab-ul Actions

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper (Cartestraina - Engleză)
        run: python -m scraper.cli --language engleza --module categorie --max-pages 2 --out data/output.ndjson --out-csv data/output.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cartestraina-data
          path: data/*.*
