name: Monitor materiale didactice

on:
  workflow_dispatch:   # rulează manual, fără schedule

jobs:
  batch1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install requests beautifulsoup4 lxml openpyxl

      - name: Run monitor script (batch 1)
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 0
          END_INDEX: 2500

      - uses: actions/upload-artifact@v4
        with:
          name: produse-1-2500
          path: produse_1_2500.xlsx

  batch2:
    runs-on: ubuntu-latest
    needs: batch1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install requests beautifulsoup4 lxml openpyxl

      - name: Run monitor script (batch 2)
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 2500
          END_INDEX: 5000

      - uses: actions/upload-artifact@v4
        with:
          name: produse-2501-5000
          path: produse_2501_5000.xlsx

      - name: Send Discord alert
        run: |
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="✅ Scanarea materialedidactice.ro s-a terminat la $DATE UTC!\nAu fost procesate batch-urile 1–2500 și 2501–5000.\n➡️ Artifactele sunt gata aici: $RUN_URL"
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
