name: Monitor materiale didactice

on:
  workflow_dispatch:   # rulează manual
  schedule:
    - cron: "0 6 */2 * *"   # rulează o dată la 2 zile la 06:00 UTC

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml openpyxl

      - name: Run monitor script
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 0
          END_INDEX: 100

      - name: Upload artifact (produse)
        uses: actions/upload-artifact@v4
        with:
          name: produse-100
          path: |
            produse_*.xlsx
