name: Monitor materiale didactice

on:
  workflow_dispatch:       # rulare manuală
  schedule:
    - cron: "0 6 */2 * *"  # rulează o dată la 2 zile, ora 06:00 UTC

jobs:
  batch-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 1
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 0
          END_INDEX: 1000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-1
          path: produse_1_1000.xlsx

  batch-2:
    runs-on: ubuntu-latest
    needs: batch-1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 2
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 1000
          END_INDEX: 2000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-2
          path: produse_1001_2000.xlsx

  batch-3:
    runs-on: ubuntu-latest
    needs: batch-2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 3
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 2000
          END_INDEX: 3000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-3
          path: produse_2001_3000.xlsx

  batch-4:
    runs-on: ubuntu-latest
    needs: batch-3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 4
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 3000
          END_INDEX: 4000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-4
          path: produse_3001_4000.xlsx

  batch-5:
    runs-on: ubuntu-latest
    needs: batch-4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 5
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 4000
          END_INDEX: 5000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-5
          path: produse_4001_5000.xlsx

  batch-6:
    runs-on: ubuntu-latest
    needs: batch-5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 6
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 5000
          END_INDEX: 6000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-6
          path: produse_5001_6000.xlsx

  batch-7:
    runs-on: ubuntu-latest
    needs: batch-6
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 7
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 6000
          END_INDEX: 7000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-7
          path: produse_6001_7000.xlsx

  batch-8:
    runs-on: ubuntu-latest
    needs: batch-7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 8
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 7000
          END_INDEX: 8000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-8
          path: produse_7001_8000.xlsx

  batch-9:
    runs-on: ubuntu-latest
    needs: batch-8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 9
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 8000
          END_INDEX: 9000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-9
          path: produse_8001_9000.xlsx

  batch-10:
    runs-on: ubuntu-latest
    needs: batch-9
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 10
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 9000
          END_INDEX: 10000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-10
          path: produse_9001_10000.xlsx

  batch-11:
    runs-on: ubuntu-latest
    needs: batch-10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 11
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 10000
          END_INDEX: 11000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-11
          path: produse_10001_11000.xlsx

  batch-12:
    runs-on: ubuntu-latest
    needs: batch-11
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 12
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 11000
          END_INDEX: 12000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-12
          path: produse_11001_12000.xlsx

  batch-13:
    runs-on: ubuntu-latest
    needs: batch-12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 13
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 12000
          END_INDEX: 13000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-13
          path: produse_12001_13000.xlsx

  batch-14:
    runs-on: ubuntu-latest
    needs: batch-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 14
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 13000
          END_INDEX: 14000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-14
          path: produse_13001_14000.xlsx

  batch-15:
    runs-on: ubuntu-latest
    needs: batch-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml openpyxl
      - name: Run scan batch 15
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 14000
          END_INDEX: 15000
      - uses: actions/upload-artifact@v4
        with:
          name: produse-batch-15
          path: produse_14001_15000.xlsx
