name: Monitor materiale didactice

on:
  workflow_dispatch:   # rulează manual

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml openpyxl

      - name: Run monitor script
        run: python scan_materiale_didactice.py
        env:
          START_INDEX: 0
          END_INDEX: 50

      - name: Upload produse.xlsx
        uses: actions/upload-artifact@v4
        with:
          name: produse
          path: produse.xlsx

      - name: Upload produse_noi.xlsx
        uses: actions/upload-artifact@v4
        with:
          name: produse_noi
          path: produse_noi.xlsx
